// <auto-generated />
namespace AgenciaBancaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mudancasnatabeladecartoesecontas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mudancasnatabeladecartoesecontas));
        
        string IMigrationMetadata.Id
        {
            get { return "201804240115151_Mudancas na tabela de cartoes e contas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
