// <auto-generated />
namespace AgenciaBancaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mudancasnastabelasclienteeconta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mudancasnastabelasclienteeconta));
        
        string IMigrationMetadata.Id
        {
            get { return "201804211541162_Mudancas nas tabelas cliente e conta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
